development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: photo_wall_dev
  pool: 5
  username: <%= ENV['USER'] %>
  password: <%= ENV['PASSWORD'] %>

test: &test
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: photo_wall_test
  pool: 5
  username: <%= ENV['USER'] %>
  password: <%= ENV['PASSWORD'] %>
